/* Matrix view — ATT&CK tactics × techniques heatmap driven by the threat profile. */

import { S, esc, profileHeat } from './app.js'

export const Matrix = (() => {

  function heatColor(count, max) {
    if (!count) return null;
    const t = Math.min(1, count / max);
    // dark slate -> teal
    return window.d3.interpolateRgb("#233047", "#2dd4bf")(0.15 + 0.85 * t);
  }

  function render() {
    S.dirty.matrix = false;
    const onlyProfile = document.getElementById("matrix-only-profile").checked;
    const showSubs = document.getElementById("matrix-show-subs").checked;
    const heat = profileHeat();

    document.getElementById("matrix-mode").innerHTML = heat.isFallback
      ? `Heatmap: <b>all ${heat.size} groups</b> (build a threat profile to focus it)`
      : `Heatmap: <b>threat profile</b> (${heat.size} ${heat.size === 1 ? "entity" : "entities"})`;

    const max = Math.max(1, ...[...heat.rolled.values()].map((r) => r.count));
    const container = document.getElementById("matrix");
    const cols = [];

    for (const tactic of S.data.tactics) {
      const techIds = S.idx.techByTactic.get(tactic.shortname) || [];
      const cells = [];

      for (const tid of techIds) {
        const rec = heat.rolled.get(tid);
        const count = rec ? rec.count : 0;
        if (onlyProfile && !count) continue;
        cells.push(cellHtml(tid, count, max, rec, false));

        if (showSubs) {
          for (const sub of S.idx.subsOf.get(tid) || []) {
            const srec = heat.exact.get(sub);
            const scount = srec ? srec.count : 0;
            if (onlyProfile && !scount) continue;
            cells.push(cellHtml(sub, scount, max, srec, true));
          }
        }
      }

      cols.push(`
        <div class="m-col">
          <div class="m-head" data-id="${tactic.id}">
            <span>${esc(tactic.name)}</span>
            <span class="m-count">${cells.length}</span>
          </div>
          ${cells.join("")}
        </div>`);
    }

    container.innerHTML = cols.join("");

    container.querySelectorAll(".m-cell").forEach((c) =>
      c.addEventListener("click", () => window.Panel.show(c.dataset.id)));
    container.querySelectorAll(".m-head").forEach((h) =>
      h.addEventListener("click", () => window.Panel.show(h.dataset.id)));
  }

  function cellHtml(tid, count, max, rec, isSub) {
    const t = S.data.techniques[tid];
    const bg = heatColor(count, max);
    const hot = count / max > 0.55;
    const title = rec
      ? `${tid} ${t.name}\nUsed by ${count}: ${rec.who.join(", ")}${count > rec.who.length ? "…" : ""}`
      : `${tid} ${t.name}`;
    return `
      <div class="m-cell${isSub ? " sub" : ""}${bg ? " heat" : ""}${hot ? " hot" : ""}"
           data-id="${tid}" title="${esc(title)}"
           ${bg ? `style="background:${bg}"` : ""}>
        <span class="m-name">${isSub ? "↳ " : ""}${esc(t.name)}</span>
        ${count ? `<span class="m-badge">${count}</span>` : ""}
      </div>`;
  }

  /* ATT&CK Navigator layer export (layer format 4.5). */
  function exportLayer() {
    const heat = profileHeat();
    const names = S.profile.size
      ? [...S.profile].map((id) => window.Panel.show(id)).join(", ")
      : "All ATT&CK groups";

    const techniques = [...heat.exact.entries()].map(([tid, rec]) => ({
      techniqueID: tid,
      score: rec.count,
      comment: `Used by: ${rec.who.join(", ")}${rec.count > rec.who.length ? "…" : ""}`,
    }));

    const layer = {
      name: `Threat profile — ${names}`.slice(0, 120),
      versions: { attack: String(parseInt(S.data.attackVersion) || ""), navigator: "5.1.0", layer: "4.5" },
      domain: "enterprise-attack",
      description: `Generated by ATT&CK Analysis Workbench. Profile: ${names}`,
      sorting: 3,
      techniques,
      gradient: {
        colors: ["#233047", "#2dd4bf"],
        minValue: 0,
        maxValue: Math.max(1, ...techniques.map((t) => t.score)),
      },
    };

    const blob = new Blob([JSON.stringify(layer, null, 2)], { type: "application/json" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "threat-profile-layer.json";
    a.click();
    URL.revokeObjectURL(a.href);
  }

  function init() {
    document.getElementById("matrix-only-profile").addEventListener("change", render);
    document.getElementById("matrix-show-subs").addEventListener("change", render);
    document.getElementById("export-layer").addEventListener("click", exportLayer);
  }

  return { init, render };
})();
